services:
  #mysql:
  #  image: 'mysql:latest'
  #  environment:
  #    - 'MYSQL_DATABASE=mydatabase'
  #    - 'MYSQL_PASSWORD=secret'
  #    - 'MYSQL_ROOT_PASSWORD=verysecret'
  #    - 'MYSQL_USER=myuser'
  #  ports:
  #    - '3306'
  db:
    container_name: 'postgres'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'PGDATA=/data/postgres'
    volumes:
      - 'db:/data/postgres'
    ports:
      - '5433:5432'
    networks:
      - 'db'
    restart: 'unless-stopped'
networks:
  db:
    driver: 'bridge'
volumes:
  db:          
  #sqlserver:
  #  image: 'mcr.microsoft.com/mssql/server:latest'
  #  environment:
  #    - 'ACCEPT_EULA=yes'
  #    - 'MSSQL_PID=express'
  #    - 'MSSQL_SA_PASSWORD=verYs3cret'
  #  ports:
  #    - '1433'
